### ISSUE TITLE
Error: Cannot tap ros/hydro: invalid syntax in tap!

### ISSUE THREAD

**Issue by srnand** [ros/homebrew-hydro#29]
I am trying to install ros hydro in macOS.

it gives this error.
brew tap ros/hydro
==> Tapping ros/hydro
Cloning into '/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro'...
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 13 (delta 1), reused 8 (delta 1), pack-reused 0
Unpacking objects: 100% (13/13), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/uuid.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/uuid.rb:7:in `<class:Uuid>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/openni2.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/openni2.rb:6:in `<class:Openni2>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/icon-naming-utils.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/icon-naming-utils.rb:6:in `<class:IconNamingUtils>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/tango-icon-theme.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/tango-icon-theme.rb:6:in `<class:TangoIconTheme>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/mongodb-dev.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/mongodb-dev.rb:6:in `<class:MongodbDev>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/yaml-cpp-0.3.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/yaml-cpp-0.3.rb:6:in `<class:YamlCpp03>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/pyassimp.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/pyassimp.rb:6:in `<class:Pyassimp>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/gfortran.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/gfortran.rb:11:in `<class:Gfortran>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/pcl.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/pcl.rb:6:in `<class:Pcl>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap ros/hydro: invalid syntax in tap!

**Comment by wjwwood** [comment]
ROS Hydro is EOL, I won't be spending time keeping this repository up-to-date. You might be able to use https://github.com/ros/homebrew-deps instead.
